import "./globals.css";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import Script from "next/script";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "InVITE",
  // description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} w-screen flex justify-center items-center`}
      >
        <div className="max-w-[1440px] basis-full max-[780px]">{children}</div>
      </body>
    </html>
  );
}
